<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, RouterLink } from "vue-router";
import { Check, ChevronRight, CircleAlert, Database, Edit3, FileCode2, HardDriveDownload, LoaderCircle, Play, RefreshCw, ShieldCheck, Users } from "@lucide/vue";
import StatusBadge from "../components/StatusBadge.vue";
import ConfirmDialog from "../components/ConfirmDialog.vue";
import { useSitesStore } from "../stores/sites";
import { appApi } from "../services/tauri";
import type { MaintenanceRun, ScanResult, UpdateItem } from "../types";
import { formatDate } from "../utils/format";

const route = useRoute(); const store = useSitesStore();
const site = computed(() => store.byId.get(String(route.params.id)));
const tabs = ["Overzicht", "Updates", "Security", "Gebruikers", "Bestanden", "Database", "Onderhoud", "Historie"];
const activeTab = ref("Overzicht"); const scan = ref<ScanResult>(); const updates = ref<UpdateItem[]>([]); const history = ref<MaintenanceRun[]>([]); const busy = ref<string>(); const confirmUpdate = ref<UpdateItem | "all" | "maintenance">(); const error = ref<string>();
const updateKinds = computed(() => ({ plugins: updates.value.filter((item) => item.kind === "plugin").length, themes: updates.value.filter((item) => item.kind === "theme").length, core: updates.value.filter((item) => item.kind === "core").length }));
const visibleChecks = computed(() => { if (!scan.value) return []; if (activeTab.value === "Gebruikers") return scan.value.checks.filter((check) => check.key === "users"); if (activeTab.value === "Bestanden") return scan.value.checks.filter((check) => ["php_files", "php_uploads", "modified_files", "permissions"].includes(check.key)); if (activeTab.value === "Database") return scan.value.checks.filter((check) => check.key === "database"); return scan.value.checks; });
async function load() { if (!site.value) return; try { [updates.value, history.value] = await Promise.all([appApi.checkUpdates(site.value.id), appApi.listHistory(site.value.id)]); } catch { /* A fresh or offline site can have no remote details yet. */ } }
async function runScan() { if (!site.value) return; busy.value = "scan"; error.value = undefined; try { scan.value = await appApi.scanSite(site.value.id); activeTab.value = "Security"; await store.load(); } catch (cause) { error.value = cause instanceof Error ? cause.message : String(cause); } finally { busy.value = undefined; } }
async function executeConfirmed() { if (!site.value || !confirmUpdate.value) return; const action = confirmUpdate.value; busy.value = "action"; try { if (action === "maintenance") { const run = await appApi.runMaintenance(site.value.id); history.value.unshift(run); activeTab.value = "Onderhoud"; } else if (action === "all") await appApi.runUpdate(site.value.id, "all"); else await appApi.runUpdate(site.value.id, action.kind, action.slug); updates.value = await appApi.checkUpdates(site.value.id); confirmUpdate.value = undefined; } catch (cause) { error.value = cause instanceof Error ? cause.message : String(cause); } finally { busy.value = undefined; } }
onMounted(load);
</script>

<template>
  <div v-if="site" class="site-detail">
    <section class="site-hero card"><div class="site-avatar xlarge">{{ site.name.slice(0, 2).toUpperCase() }}</div><div class="site-hero-copy"><div><h2>{{ site.name }}</h2><StatusBadge :status="site.status" /></div><span class="site-url">{{ site.url }}</span><p>{{ site.sshUsername }}@{{ site.sshHost }} · {{ site.wordpressPath }}</p></div><div class="hero-actions"><RouterLink class="button secondary" :to="`/websites/${site.id}/bewerken`"><Edit3 :size="16" /> Bewerken</RouterLink><button class="button secondary" :disabled="!!busy" @click="runScan"><LoaderCircle v-if="busy === 'scan'" class="spin" :size="17" /><RefreshCw v-else :size="17" /> Website controleren</button><button class="button primary" :disabled="!!busy" @click="confirmUpdate = 'maintenance'"><Play :size="17" /> Onderhoud uitvoeren</button></div></section>
    <nav class="tabs" aria-label="Websiteonderdelen"><button v-for="tab in tabs" :key="tab" :class="{ active: activeTab === tab }" @click="activeTab = tab">{{ tab }}<span v-if="tab === 'Updates' && updates.length">{{ updates.length }}</span></button></nav>
    <p v-if="error" class="error-banner">{{ error }}</p>

    <template v-if="activeTab === 'Overzicht'"><div class="detail-stat-grid"><article class="card detail-stat"><span><RefreshCw /></span><small>Beschikbare updates</small><strong>{{ updates.length }}</strong><p>{{ updateKinds.core }} core · {{ updateKinds.plugins }} plugins · {{ updateKinds.themes }} thema's</p></article><article class="card detail-stat"><span><ShieldCheck /></span><small>Laatste securityscan</small><strong>{{ site.securityStatus ?? 'Nog niet uitgevoerd' }}</strong><p>{{ formatDate(site.lastScanAt) }}</p></article><article class="card detail-stat"><span><HardDriveDownload /></span><small>Laatste onderhoud</small><strong>{{ formatDate(site.lastMaintenanceAt) }}</strong><p>{{ history[0]?.status === 'success' ? 'Succesvol afgerond' : 'Geen resultaat' }}</p></article></div><section class="card info-card"><div class="card-header"><div><h3>Technische basisinformatie</h3><p>Automatisch uitgelezen via vooraf ingestelde controles.</p></div></div><dl class="info-list"><div><dt>WordPress-versie</dt><dd>{{ site.wordpressVersion ?? 'Onbekend' }}</dd></div><div><dt>PHP-versie</dt><dd>{{ site.phpVersion ?? 'Onbekend' }}</dd></div><div><dt>SSH host key</dt><dd>{{ site.pinnedHostKey ? 'Vastgezet en gecontroleerd' : 'Nog niet geaccepteerd' }}</dd></div><div><dt>Laatste scan</dt><dd>{{ formatDate(site.lastScanAt) }}</dd></div></dl></section></template>

    <section v-else-if="activeTab === 'Updates'" class="card table-card"><div class="card-header"><div><h3>Beschikbare updates</h3><p>Controleer versies voordat je wijzigingen uitvoert.</p></div><button v-if="updates.length" class="button primary" @click="confirmUpdate = 'all'">Alles bijwerken</button></div><div v-if="!updates.length" class="empty-state"><Check :size="38" /><h3>Alles is bijgewerkt</h3><p>Er zijn momenteel geen WordPress-, plugin- of thema-updates.</p></div><table v-else><thead><tr><th>Onderdeel</th><th>Type</th><th>Huidige versie</th><th>Nieuwe versie</th><th></th></tr></thead><tbody><tr v-for="item in updates" :key="`${item.kind}-${item.slug}`"><td><strong>{{ item.name }}</strong><small>{{ item.slug }}</small></td><td class="capitalize">{{ item.kind }}</td><td>{{ item.currentVersion }}</td><td><strong>{{ item.newVersion }}</strong></td><td><button class="button small secondary" @click="confirmUpdate = item">Bijwerken</button></td></tr></tbody></table></section>

    <template v-else-if="activeTab === 'Security' || activeTab === 'Gebruikers' || activeTab === 'Bestanden' || activeTab === 'Database'"><section class="card scan-section"><div class="card-header"><div><h3>{{ activeTab === 'Security' ? 'Uitgevoerde securitycontroles' : activeTab }}</h3><p>Resultaten zijn feitelijke controlepunten en geen garantie dat de website volledig veilig is.</p></div><button class="button secondary" :disabled="!!busy" @click="runScan">Securityscan uitvoeren</button></div><div v-if="!scan" class="empty-state compact"><component :is="activeTab === 'Gebruikers' ? Users : activeTab === 'Bestanden' ? FileCode2 : activeTab === 'Database' ? Database : ShieldCheck" :size="38" /><h3>Nog geen resultaten in deze sessie</h3><p>Voer een scan uit om actuele resultaten te laden.</p></div><div v-else class="check-list"><article v-for="check in visibleChecks" :key="check.key" class="check-row"><span :class="['check-symbol', check.status]"><Check v-if="check.status === 'success'" /><CircleAlert v-else /></span><div><h4>{{ check.label }}</h4><p>{{ check.summary }}</p><div v-for="finding in check.findings" :key="finding.path ?? finding.title" class="finding"><strong>{{ finding.title }}</strong><p>{{ finding.detail }}</p><code v-if="finding.path">{{ finding.path }}</code></div></div><StatusBadge :status="check.status" /></article></div></section></template>

    <section v-else-if="activeTab === 'Onderhoud'" class="maintenance-layout"><div class="card maintenance-intro"><span class="section-icon"><Play /></span><div><h3>Volledige onderhoudsrun</h3><p>We voeren voorcontroles uit, maken eerst een lokale databasebackup, werken gecontroleerd bij en controleren de website daarna opnieuw.</p></div><button class="button primary" @click="confirmUpdate = 'maintenance'">Onderhoud uitvoeren</button></div><article v-if="history[0]" class="card run-detail"><div class="card-header"><div><h3>Laatste onderhoud</h3><p>{{ formatDate(history[0].startedAt) }}</p></div><StatusBadge :status="history[0].status" /></div><ol class="step-list"><li v-for="step in history[0].steps" :key="step.key" :class="step.status"><span><Check v-if="step.status === 'success'" :size="15" /><LoaderCircle v-else-if="step.status === 'running'" class="spin" :size="15" /></span><strong>{{ step.label }}</strong><small>{{ step.detail }}</small></li></ol></article></section>
    <section v-else-if="activeTab === 'Historie'" class="card table-card"><div class="card-header"><div><h3>Onderhoudshistorie</h3><p>Vergelijk eerdere onderhoudsbeurten.</p></div></div><table><thead><tr><th>Datum</th><th>Resultaat</th><th>Voor</th><th>Na</th><th></th></tr></thead><tbody><tr v-for="run in history" :key="run.id"><td>{{ formatDate(run.startedAt) }}</td><td><StatusBadge :status="run.status" /></td><td>{{ run.beforeVersions }}</td><td>{{ run.afterVersions }}</td><td><ChevronRight :size="17" /></td></tr></tbody></table></section>
  </div>
  <div v-else class="empty-state card"><h3>Website niet gevonden</h3><RouterLink class="button secondary" to="/websites">Terug naar websites</RouterLink></div>

  <ConfirmDialog v-if="confirmUpdate" :title="confirmUpdate === 'maintenance' ? 'Onderhoud uitvoeren?' : confirmUpdate === 'all' ? `${updates.length} updates uitvoeren?` : `${confirmUpdate.name} bijwerken?`" :confirm-label="confirmUpdate === 'maintenance' ? 'Onderhoud starten' : 'Bijwerken'" :busy="busy === 'action'" @cancel="confirmUpdate = undefined" @confirm="executeConfirmed"><template v-if="confirmUpdate === 'maintenance'"><p>De app maakt eerst een databasebackup. Als die mislukt, worden er geen updates gestart.</p><ul><li>Voorcontrole en securitychecks</li><li>Lokale databasebackup</li><li>Core, plugins, thema's en vertalingen</li><li>Database- en homepagecontrole</li></ul></template><template v-else-if="confirmUpdate === 'all'"><ul><li v-for="item in updates" :key="item.slug">{{ item.name }}: {{ item.currentVersion }} → {{ item.newVersion }}</li></ul></template><p v-else>{{ confirmUpdate.name }} wordt bijgewerkt van {{ confirmUpdate.currentVersion }} naar {{ confirmUpdate.newVersion }}.</p></ConfirmDialog>
</template>
